In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.random.randn(100)

In [3]:
data

array([-0.14742969, -0.38212638,  2.16980637, -0.73686503,  2.40091257,
       -0.89170376,  0.37051036, -1.92475076, -0.25736362, -1.46639614,
       -0.92313554, -0.32032103, -0.16580899, -1.73280285, -1.12677337,
        0.21261417, -0.37416303,  1.1542141 ,  0.33207367,  0.13621365,
        0.68693062,  0.24519605,  0.06827821, -0.63073987, -0.91845372,
       -0.14956087,  0.83951088, -1.02484092, -0.75669439, -0.75139677,
       -1.29404265,  2.93162652,  0.50111987,  0.15694996, -1.44646312,
       -0.83299345,  1.56621513,  0.65279535,  0.92411443,  1.62185467,
        0.87964149,  0.37942116, -1.22203512,  1.46617132,  0.1483399 ,
        0.22956843, -0.88184245,  2.33573748, -0.54568748, -0.99300012,
       -0.67204177, -1.05709602, -0.7480648 ,  0.40007245,  1.66380125,
        0.75016865,  1.34022688, -0.55975403, -0.03165037, -1.17251392,
        0.93648006,  0.28593842, -0.29554232,  0.55124268, -0.23731107,
        1.185863  ,  0.77604248, -0.11918951, -0.03882775, -0.18319129,
        2.00299569, -1.40168307,  1.57086223,  0.77933299, -0.90084837,
       -1.03059111, -1.04220352, -0.43088522,  0.05070126, -0.44270118,
        0.69746054,  1.00012579, -0.80476004, -1.7552041 , -0.49697828,
       -1.39629987, -0.95857346, -0.11038228,  1.26293312, -0.92896218,
        0.54926019,  0.8945107 ,  0.19520021,  0.13769697, -0.0801944 ,
        0.07485918,  1.11932573, -1.47922071, -0.6450088 ,  0.27818116])

In [10]:
labels = ["A","B","C","D","E","F","G","H","I","J"]
df = pd.DataFrame(data.reshape(10,10)**2,columns=labels)

In [18]:
def normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

In [20]:
df_normal = normalize(df)

In [22]:
df_normal["new"] = np.random.rand(10)

In [26]:
df_normal.drop("new",axis=1,inplace=True)

In [27]:
df_normal

,A,B,C,D,E,F,G,H,I,J
0,0.000000,0.010065,1.000000,0.171145,1.000000,0.406127,0.000000,0.678330,0.040925,0.816186
1,0.208118,0.004978,0.004854,0.974480,0.219381,0.020370,0.001175,0.242496,0.068552,0.000000
2,0.112809,0.000000,0.000000,0.123742,0.145386,0.008624,0.245061,0.190708,0.358585,0.209063
3,0.414212,1.000000,0.052400,0.001853,0.362251,0.354042,1.000000,0.076046,0.535123,1.000000
4,0.188468,0.009824,0.316518,0.695901,0.002705,0.024227,0.276527,1.000000,0.186182,0.370424
5,0.107739,0.123892,0.117987,0.046083,0.479650,0.286592,0.716368,0.055321,0.000000,0.519260
6,0.214337,0.002536,0.017579,0.093053,0.008664,0.720489,0.200783,0.000371,0.000317,0.005745
7,1.000000,0.223169,0.523653,0.192176,0.139823,0.543461,0.409763,0.031869,0.000984,0.067933
8,0.116463,0.110159,0.136705,1.000000,0.041778,1.000000,0.337508,0.000000,1.000000,0.323301
9,0.070159,0.086712,0.007110,0.000000,0.000000,0.000000,0.481749,0.399727,0.260373,0.022524

In [32]:
df_normal["A"] = df_normal["B"]

In [37]:
df_normal[["A","C"]] = df_normal[["B","B"]]

In [38]:
df_normal

,A,B,C,D,E,F,G,H,I,J
0,0.010065,0.010065,0.010065,0.171145,1.000000,0.406127,0.000000,0.678330,0.040925,0.816186
1,0.004978,0.004978,0.004978,0.974480,0.219381,0.020370,0.001175,0.242496,0.068552,0.000000
2,0.000000,0.000000,0.000000,0.123742,0.145386,0.008624,0.245061,0.190708,0.358585,0.209063
3,1.000000,1.000000,1.000000,0.001853,0.362251,0.354042,1.000000,0.076046,0.535123,1.000000
4,0.009824,0.009824,0.009824,0.695901,0.002705,0.024227,0.276527,1.000000,0.186182,0.370424
5,0.123892,0.123892,0.123892,0.046083,0.479650,0.286592,0.716368,0.055321,0.000000,0.519260
6,0.002536,0.002536,0.002536,0.093053,0.008664,0.720489,0.200783,0.000371,0.000317,0.005745
7,0.223169,0.223169,0.223169,0.192176,0.139823,0.543461,0.409763,0.031869,0.000984,0.067933
8,0.110159,0.110159,0.110159,1.000000,0.041778,1.000000,0.337508,0.000000,1.000000,0.323301
9,0.086712,0.086712,0.086712,0.000000,0.000000,0.000000,0.481749,0.399727,0.260373,0.022524